version: '3'


services:
  ros_ws:
    image: georgedaoudontechu/ros_ws
    container_name: ros_ws
    environment:
      DISPLAY: "host.docker.internal:0.0"
    command: tail -F anything 
    network_mode: "host"
    volumes:
      - ./code:/code
      #- ./src:/root/catkin_ws/src